### PR TITLE
Update L2_principal_component_analysis.ipynb

### PR DESCRIPTION
**Pull request by alexkjames**
include mcpca, resolution, and time_coverage_plot in the pca notebook

### CODE REVIEW

**Review by CommonClimate — CHANGES_REQUESTED** [review]
Nice work! The notebook looks great and I really like the addition of `time_coverage_plot()` and `resolution()`.   A couple of suggestions:
- please add your name and ORCID to the authors
- The default exponential distribution is not a very good model for those kinds of uncertainties. I recommend using the `random_choice` method instead. I'm happy to talk you through how it works.

**Comment by alexkjames** [comment]
> Nice work! The notebook looks great and I really like the addition of `time_coverage_plot()` and `resolution()`. A couple of suggestions:
> 
>     * please add your name and ORCID to the authors
> 
>     * The default exponential distribution is not a very good model for those kinds of uncertainties. I recommend using the `random_choice` method instead. I'm happy to talk you through how it works.

I'm familiar with the random choice method, though I'm not sure how to create realistic looking age ensembles with it. By nature its discrete, so it produces pretty jagged looking ensembles (from my brief experimentation anyway). From what I can tell, the poisson distribution seems to create more realistic looking ensembles because it samples from a continuous distribution. 

I'd show a visualization of the ensembles in the notebook, we just don't have a stackplot method for `MulEnsGeoSeries` objects yet (I've created an issue to address this)

**Comment by CommonClimate** [comment]
L2_correlations.ipynb has the answer! You can generate your time perturbations this way, and simply add them to the original time:
```
pert = pyleo.utils.tsmodel.random_time_axis(n,
                                         delta_t_dist='random_choice',
                                         param =[[-0.1,0,0.1],[0.02,0.96,0.02]])
```

**Comment by alexkjames** [comment]
Ran into conflict issues, opened a new PR #67

**Pull request closed without merging**
